### ISSUE TITLE
GIF screen recorder

### ISSUE THREAD

**Issue by Omar-Ebrahim-1** [serranomorante/.dotfiles#2]
Hello serranomorante,

I hope you are doing well. I am writing to ask about how you record your screen into a gif  in
![gif_software](https://github.com/serranomorante/.dotfiles/assets/117550217/dd22c718-55c1-4a43-848c-27d5d636c055)

**Comment by serranomorante** [comment]
jajaja Sure thing!

I just do `t-rec --natural --quiet` from my terminal and press `Ctrl+D` when I want to stop the recording. By default it will record the terminal you're currently in, but you can pass different properties to make it record other windows...

[This is the package](https://github.com/sassman/t-rec-rs). Be aware that it might not work on Wezterm terminal emulator, at least for me it didn't.

👍

**Comment by Omar-Ebrahim-1** [comment]
Thank you so much brother. I wish you the best.
